let pi = Math.PI.toFixed(2);
console.log(pi);
let max = Math.max(15,11,16,23,11,54,87,3,2);
console.log(max);
let rand = Math.random();
console.log(rand);
let random = Math.random()*10;
console.log(random);
let a = (1.6+1.3).toFixed(1);
console.log(a);
let num = '100$';
num = parseFloat('100$');
console.log(num);