let string = "some test string";
let a;
a = string.length;
a = string[0];
console.log(a);
a = string[string.length-1];
console.log(a);
a = `${string[0].toUpperCase()}${string.slice(1,-1)}${string[string.length-1].toUpperCase()}`;
console.log(a);
a = string.indexOf('string');
console.log(a);
a = string.indexOf(' ');
let b = string.indexOf(' ' , a+1);
console.log(b);
a = string.substr(5,4);
console.log(a);
a = string.slice(5,10);
console.log(a);
a = string.slice(0,string.length-6);
console.log(a);
let c = 20;
let d = 16;
a = String(c) + String(d);
console.log(a);